# Heuers' statistical Football model

The following implementation aims to recreate the Football model of Prof. Dr. Andreas Heuer.

In [19]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from functools import lru_cache
import warnings

NUM_OF_COUNTRIES = 5
NUM_OF_SEASONS = 25
NUM_OF_MATCHES = 9130
NUM_OF_MATCHES_IN_A_SEASON = 1826
SEED = 1893

np.random.seed(SEED)
warnings.filterwarnings('ignore')

In [20]:
# Helperfunctions
def score_from_amount_and_diff(amount, diff):
    if diff < 0:
        home_score = (amount + diff) / 2
        away_score = home_score - diff
    else:
        away_score = (amount - diff) / 2
        home_score = away_score + diff

    # cut excess floating numbers
    if (home_score - int(home_score)) == 0 and (away_score - int(away_score)) == 0:
        home_score = int(home_score)
        away_score = int(away_score)
    
    return home_score, away_score


def print_formatted_pred_score(country, season, matchnumber, ht_name, at_name, ht_pred_score, at_pred_score, ht_actual_score, at_actual_score):
    print("%4s %3s %3s %20s %20s %15s | %6s" %
          (country, season, matchnumber, ht_name, at_name,
           str(ht_pred_score)[0:4] + ":" + str(at_pred_score)[0:4],
           f"{ht_actual_score}:{at_actual_score}"))


def closed_form_solution(X, y):
    # alternative: np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, y))
    return np.linalg.solve(np.dot(X.T, X), np.dot(X.T, y))

## Step 1 - Homefieldadvantage (per country and season)

In [21]:
df_homefield = pd.read_csv('data/plot_homefield_adv.csv', sep=';')
avg_homefield_adv = np.sum(df_homefield["homefield_adv"]) / NUM_OF_SEASONS
print("Average homefield advantage on all games:", avg_homefield_adv)

Average homefield advantage on all games: 0.3683735810113519

In [22]:
df_country_season_homefield_adv = pd.read_csv(
    "data/country_season_homefield_adv.csv", sep=";")
df_country_season_homefield_adv['bias'] = 1

noise = np.random.normal(
    avg_homefield_adv, 0.01, df_country_season_homefield_adv.shape[0] * 3)

for index, row in df_country_season_homefield_adv.iterrows():
    if row["hf_adv_actual"] == 0:
        df_country_season_homefield_adv.at[index,
                                           "hf_adv_actual"] = noise[index]
    if row["hf_adv_current_season"] == 0:
        df_country_season_homefield_adv.at[index,
                                           "hf_adv_current_season"] = noise[df_country_season_homefield_adv.shape[0] + index]
    if row["hf_adv_last_three_seasons"] == 0:
        df_country_season_homefield_adv.at[index,
                                           "hf_adv_last_three_seasons"] = noise[df_country_season_homefield_adv.shape[0] * 2 + index]

df_country_season_homefield_adv

,country,season,matchnumber,hf_adv_last_three_seasons,hf_adv_current_season,hf_adv_actual,bias
0,ENG,14,1,0.360328,-0.300000,-0.6,1
1,ENG,14,2,0.369811,0.033333,0.7,1
2,ENG,14,3,0.357811,-0.075000,-0.4,1
3,ENG,14,4,0.357465,0.060000,0.6,1
4,ENG,14,5,0.361030,0.016667,-0.2,1
...,...,...,...,...,...,...,...
925,ITA,18,34,0.317094,0.262857,0.5,1
926,ITA,18,35,0.317094,0.247222,-0.3,1
927,ITA,18,36,0.317094,0.248649,0.3,1
928,ITA,18,37,0.317094,0.268421,1.0,1
929,ITA,18,38,0.317094,0.279487,0.7,1

In [23]:
#@lru_cache(maxsize=None)
def h_country_season_homefield_adv(country, season, matchnumber):
    if season == 14:
        return avg_homefield_adv
        
    sub_df = df_country_season_homefield_adv.query(
        f"country == '{country}' and season < {season} or (country == '{country}' and season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["hf_adv_last_three_seasons",
                "hf_adv_current_season"]].values # no bias
    y = sub_df["hf_adv_actual"].values

    w = closed_form_solution(X, y)
    # print("hf adv weights:", w)

    input_df = df_country_season_homefield_adv.query(
        f"country == '{country}' and season == {season} and matchnumber == {matchnumber}")
    input = input_df[["hf_adv_last_three_seasons",
                      "hf_adv_current_season"]].values

    return np.dot(w, input.T)[0]

print("Homefield advantage:", h_country_season_homefield_adv("ESP", 18, 2))

Homefield advantage: -0.17982626034923987

## Step 2 - Goalamount per match (per country and season)

there are higher scored countrys as well as lower scoring ones
for now the goalamount will be modeled as a constant

In [24]:
df_goalamount = pd.read_csv('data/plot_goalamount.csv', sep=';')
avg_goalamount = np.sum(df_goalamount["goalamount"]) / NUM_OF_SEASONS
print("Average goalamount of all games:", avg_goalamount)

Average goalamount of all games: 2.724046095631235

In [25]:
df_country_season_goalamount = pd.read_csv(
    "data/country_season_goalamount.csv", sep=";")
df_country_season_goalamount['bias'] = 1

noise = np.random.normal(
    avg_goalamount, 0.01, df_country_season_goalamount.shape[0] * 3)


for index, row in df_country_season_goalamount.iterrows():
    if row["ga_actual"] == 0:
        df_country_season_goalamount.at[index, "ga_actual"] = noise[index]
    if row["ga_current_season"] == 0:
        df_country_season_goalamount.at[index,
                                        "ga_current_season"] = noise[df_country_season_goalamount.shape[0] + index]
    if row["ga_last_three_seasons"] == 0:
        df_country_season_goalamount.at[index,
                                        "ga_last_three_seasons"] = noise[df_country_season_goalamount.shape[0] * 2 + index]

df_country_season_goalamount

,country,season,matchnumber,ga_last_three_seasons,ga_current_season,ga_actual,bias
0,ENG,14,1,2.724707,2.711666,2.6,1
1,ENG,14,2,2.738289,2.600000,2.3,1
2,ENG,14,3,2.712757,2.450000,3.2,1
3,ENG,14,4,2.738602,2.700000,3.0,1
4,ENG,14,5,2.727393,2.775000,3.2,1
...,...,...,...,...,...,...,...
925,ITA,18,34,2.735965,2.663636,2.3,1
926,ITA,18,35,2.735965,2.652941,2.9,1
927,ITA,18,36,2.735965,2.660000,3.1,1
928,ITA,18,37,2.735965,2.672222,2.8,1
929,ITA,18,38,2.735965,2.675676,2.9,1

In [26]:
#@lru_cache(maxsize=None)
def h_country_season_goalamount(country, season, matchnumber):
    if season == 14:
        return avg_goalamount
        
    sub_df = df_country_season_goalamount.query(
        f"country == '{country}' and season < {season} or (season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["ga_last_three_seasons",
                "ga_current_season"]].values  # no bias
    y = sub_df["ga_actual"].values

    w = closed_form_solution(X, y)
    # print("weights:", w)

    input_df = df_country_season_goalamount.query(
        f"country == '{country}' and season == {season} and matchnumber == {matchnumber}")
    input = input_df[["ga_last_three_seasons",
                    "ga_current_season"]].values

    return np.dot(w, input.T)[0]


print("Goalamount:", h_country_season_goalamount("GER", 16, 1))

Goalamount: 2.936261991159577

## Step 3: Teamstrength and expected goaldifference + Step 4: Specialty for promoters

In [27]:
df_matches = pd.read_csv('data/matches_heuer.csv', sep=';')
df_matches['bias'] = 1

noise = np.random.normal(0, 0.01, df_matches.shape[0] * 6)

for index, row in df_matches.iterrows():
    if row["curr_eff_chancediff"] == 0:
        df_matches.at[index, "curr_eff_chancediff"] = noise[index]
    if row["past_chancediff_combined"] == 0:
        df_matches.at[index,
                           "past_chancediff_combined"] = noise[df_matches.shape[0] + index]
    if row["curr_eff_chanceamount"] == 0:
        df_matches.at[index,
                      "curr_eff_chanceamount"] = noise[df_matches.shape[0] * 2 + index]
    if row["past_chanceamount"] == 0:
        df_matches.at[index,
                           "past_chanceamount"] = noise[df_matches.shape[0] * 3 + index]
    if row["actual_goaldiff"] == 0:
        df_matches.at[index,
                           "actual_goaldiff"] = noise[df_matches.shape[0] * 4 + index]
    if row["actual_goalamount"] == 0:
        df_matches.at[index,
                           "actual_goalamount"] = noise[df_matches.shape[0] * 5 + index]

df_matches

,country,season,matchnumber,teamname,curr_eff_chancediff,past_chancediff_combined,curr_eff_chanceamount,past_chanceamount,market_value_ln_relative,is_promoter,is_home,actual_goalamount,actual_goaldiff,bias
0,ENG,14,1,Queens Park Rangers,-0.005861,-0.006476,0.017177,-0.016672,-0.392415,True,True,1,-1,1
1,ENG,14,1,Hull,-0.001357,-0.016237,-0.001372,0.003611,-0.348740,False,False,1,1,1
2,ENG,14,1,Newcastle,-0.017697,-0.007620,-0.002578,0.010065,-0.169272,False,True,2,-2,1
3,ENG,14,1,Man City,0.004003,-0.012178,0.001265,0.005501,1.002768,False,False,2,2,1
4,ENG,14,1,Burnley,-0.004496,-0.007794,0.004065,-0.004955,-1.140622,True,True,4,-2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18255,ITA,18,38,Napoli,5.242267,5.293421,3.415385,8.877193,1.070083,False,False,5,-1,1
18256,ITA,18,38,Inter,2.881676,2.380263,1.042860,6.754386,1.024225,False,True,3,1,1
18257,ITA,18,38,Empoli,-3.462648,-3.058772,-0.805584,4.403509,-0.738824,True,False,3,-1,1
18258,ITA,18,38,Cagliari,-3.170633,-1.972368,-1.823289,4.824561,-0.358838,False,True,3,-1,1
18259,ITA,18,38,Udinese,-2.084748,-0.971053,-1.537836,5.000000,-0.098958,False,False,3,1,1

In [28]:
#@lru_cache(maxsize=None)
def h_teamstrength(country, season, matchnumber, teamname):
    if season == 14 and matchnumber == 1:
        # avg teamstrength
        return 0

    sub_df = df_matches.query(
        f"country == '{country}' and season < {season} and matchnumber == {matchnumber} or (season == {season} and matchnumber < {matchnumber})")

    sub_df["effective_chancediff"] = sub_df["curr_eff_chancediff"]
    X = sub_df[["past_chancediff_combined",
                "curr_eff_chancediff", "market_value_ln_relative"]].values # no bias
    y = []
    # one team is only responsible for half of the goaldiff
    goal_diff = sub_df["actual_goaldiff"].values
    for i in goal_diff:
        y.append(i/2)

    w = closed_form_solution(X, y)
    #print("teamstrength weights:", w)

    input_df = df_matches.query(
        f"season == {season} and matchnumber == {matchnumber} and teamname == '{teamname}'")

    # Homefield advantage correction
    homefield_matches = df_matches.query(
        f"season == {season} and matchnumber < {matchnumber} and teamname == '{teamname}' and is_home").count()["is_home"]

    if matchnumber > 1:
        additional_homefield_matches = homefield_matches - \
            ((matchnumber - 1) - homefield_matches)
        if additional_homefield_matches > 0:
            input_df["curr_eff_chancediff"] -= (additional_homefield_matches * \
                h_country_season_homefield_adv(country, season, matchnumber) * 4) / (matchnumber - 1)

    # Step 4: Specialty for promoters
    if input_df.iloc[0]["is_promoter"]:
        input_df["past_chancediff_combined"] = input_df["past_chancediff_combined"] * 0.45 * w[1]
        input_df["curr_eff_chancediff"] = input_df["curr_eff_chancediff"] * 0.45 * w[1]

    input = input_df[["past_chancediff_combined",
                      "curr_eff_chancediff", "market_value_ln_relative"]].values

    teamstrength = np.dot(w, input.T)[0]

    if input_df.iloc[0]["is_promoter"]:
        teamstrength -= (13/34)

    return teamstrength

#TODO: Current fitness value is missing -> might neglect

print("Teamstrength:", h_teamstrength("ENG", 16, 12, "Leicester"))

Teamstrength: -0.035864796493152086

## Step 5: Expected goalamount per match

In [29]:
#@lru_cache(maxsize=None)
def h_goalamount_from_avg_per_match(country, season, matchnumber, teamname):
    if season == 14 and matchnumber == 1:
        # avg goalamount from avg
        return 0

    sub_df = df_matches.query(
        f"country == '{country}' and season < {season} and matchnumber == {matchnumber} or (season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["past_chanceamount", "curr_eff_chanceamount"]].values  # no bias
    y = []
    for index, row in sub_df.iterrows():
        y.append(row["actual_goalamount"] - avg_goalamount) # - h_country_season_goalamount(row["country"], row["season"], row["matchnumber"]))

    w = closed_form_solution(X, y)
    #print("weights:", w)

    input_df = df_matches.query(
        f"season == {season} and matchnumber == {matchnumber} and teamname == '{teamname}'")
    input = input_df[["past_chanceamount", "curr_eff_chanceamount"]].values

    return np.dot(w, input.T)[0]

print("Goalamount from avg:", h_goalamount_from_avg_per_match("GER", 16, 19, "Bayern"))

Goalamount from avg: 0.21079154127213198

## Step 6: Predicted Goals

In [30]:
def predicted_goals(country, season, matchnumber, hometeam, awayteam):
    goalamount = h_goalamount_from_avg_per_match(
        country, season, matchnumber, hometeam) + h_goalamount_from_avg_per_match(country, season, matchnumber, awayteam) + h_country_season_goalamount(country, season, matchnumber)
    #goaldiff = h_country_season_homefield_adv(country, season, matchnumber) + h_teamstrength(country, season, matchnumber, hometeam) - h_teamstrength(country, season, matchnumber, awayteam)
    goaldiff = avg_homefield_adv + \
        h_teamstrength(country, season, matchnumber, hometeam) - \
        h_teamstrength(country, season, matchnumber, awayteam)
    return (goalamount, goaldiff)

## Step 7: Dependence on matchnumber

In [31]:
def matchnumber_goalamount_multiplier(country, matchnumber):
    # Uncertain
    if country == 'GER':
        if matchnumber < 18:
            return 1.02
        elif matchnumber < 31:
            return 0.95
        else:
            return 1.2
    else:
        if matchnumber < 19:
            return 1.02
        elif matchnumber < 35:
            return 0.95
        else:
            return 1.2

## Final: Full run on dataset to measure goalamount and goaldifference error

In [32]:
def predict(country, season, matchnumber, hometeam, awayteam):
    amount, diff = predicted_goals(country, season, matchnumber, hometeam, awayteam)

    home_score, away_score = score_from_amount_and_diff(amount, diff)

    home_score *= matchnumber_goalamount_multiplier(country, matchnumber)
    away_score *= matchnumber_goalamount_multiplier(country, matchnumber)

    return (home_score+ away_score), (home_score - away_score)

In [33]:
# For match in Dataset run prediction and measure error
do_a_whole_run = True

if not do_a_whole_run:
    print("Skipped whole run")

test_df = df_matches.query(f"season == 18")
ga_squared_error, gd_squared_error = 0, 0

if do_a_whole_run:
    for index, row in test_df.iterrows():
        if index % 2 == 0:
            home_score, away_score = score_from_amount_and_diff(
                row["actual_goalamount"], row["actual_goaldiff"])
            hometeam = row["teamname"]
            continue
        else:
            awayteam = row["teamname"]
            ga_pred, gd_pred = predict(
                row["country"], row["season"], row["matchnumber"], hometeam, awayteam)
            ga_squared_error += np.square(ga_pred - row["actual_goalamount"])
            gd_squared_error += np.square(gd_pred - row["actual_goaldiff"])
            h_score_pred, a_score_pred = score_from_amount_and_diff(ga_pred,gd_pred)
            print_formatted_pred_score(row["country"], row["season"], row["matchnumber"], hometeam, awayteam, h_score_pred ,a_score_pred, home_score, away_score)

    print("Squared error goalamount",
          ga_squared_error / NUM_OF_MATCHES_IN_A_SEASON)
    print("Squared error goaldiff", gd_squared_error / NUM_OF_MATCHES_IN_A_SEASON)

 ENG  18   1               Wolves              Everton       1.42:1.63 |    2:2
 ENG  18   1              Watford             Brighton       1.99:1.46 |    2:0
 ENG  18   1          Southampton              Burnley       1.87:1.35 |    0:0
 ENG  18   1            Newcastle            Tottenham       1.61:1.76 |    1:2
 ENG  18   1              Man Utd            Leicester       2.05:1.39 |    2:1
 ENG  18   1              Arsenal             Man City       1.93:1.82 |    0:2
 ENG  18   1         Huddersfield              Chelsea       1.51:2.01 |    0:3
 ENG  18   1               Fulham       Crystal Palace       1.52:1.59 |    0:2
 ENG  18   1          Bournemouth              Cardiff       2.02:0.84 |    2:0
 ENG  18   1            Liverpool             West Ham       2.29:1.38 |    4:0
 ENG  18   2            Tottenham               Fulham       1.97:0.47 |    3:1
 ENG  18   2              Everton          Southampton       1.61:0.87 |    2:1
 ENG  18   2             West Ham          Bournemouth       1.33:1.16 |    1:2
 ENG  18   2             Brighton              Man Utd       0.99:1.51 |    3:2
 ENG  18   2              Burnley              Watford       1.38:1.14 |    1:3
 ENG  18   2              Cardiff            Newcastle       1.15:1.40 |    0:0
 ENG  18   2              Chelsea              Arsenal       1.66:0.73 |    3:2
 ENG  18   2             Man City         Huddersfield       2.11:0.33 |    6:1
 ENG  18   2            Leicester               Wolves       1.69:0.82 |    2:0
 ENG  18   2       Crystal Palace            Liverpool       0.99:1.40 |    0:2
 ENG  18   3               Wolves             Man City       1.07:1.93 |    1:1
 ENG  18   3              Man Utd            Tottenham       1.52:1.35 |    0:3
 ENG  18   3         Huddersfield              Cardiff       1.45:0.89 |    0:0
 ENG  18   3          Bournemouth              Everton       1.47:1.28 |    2:2
 ENG  18   3            Newcastle              Chelsea       1.19:1.61 |    1:2
 ENG  18   3              Watford       Crystal Palace       1.57:1.22 |    2:1
 ENG  18   3              Arsenal             West Ham       1.66:0.89 |    3:1
 ENG  18   3            Liverpool             Brighton       2.07:0.66 |    1:0
 ENG  18   3          Southampton            Leicester       1.40:1.13 |    1:2
 ENG  18   3               Fulham              Burnley       1.39:1.22 |    4:2
 ENG  18   4              Watford            Tottenham       1.58:1.85 |    2:1
 ENG  18   4             Man City            Newcastle       2.28:1.12 |    2:1
 ENG  18   4             West Ham               Wolves       1.79:0.99 |    0:1
 ENG  18   4       Crystal Palace          Southampton       1.64:1.30 |    0:2
 ENG  18   4              Chelsea          Bournemouth       2.14:1.15 |    2:0
 ENG  18   4              Burnley              Man Utd       1.34:1.61 |    0:2
 ENG  18   4              Everton         Huddersfield       1.88:0.90 |    1:1
 ENG  18   4              Cardiff              Arsenal       1.09:1.86 |    2:3
 ENG  18   4             Brighton               Fulham       1.74:1.14 |    2:2
 ENG  18   4            Leicester            Liverpool       1.60:1.72 |    1:2
 ENG  18   5               Wolves              Burnley       1.45:1.22 |    1:0
 ENG  18   5         Huddersfield       Crystal Palace       1.39:1.29 |    0:1
 ENG  18   5            Tottenham            Liverpool       1.70:1.36 |    1:2
 ENG  18   5            Newcastle              Arsenal       1.38:1.50 |    1:2
 ENG  18   5              Everton             West Ham       1.64:1.10 |    1:3
 ENG  18   5          Bournemouth            Leicester       1.52:1.24 |    4:2
 ENG  18   5              Watford              Man Utd       1.39:1.51 |    1:2
 ENG  18   5              Chelsea              Cardiff       2.13:0.68 |    4:1
 ENG  18   5             Man City               Fulham       2.31:0.83 |    3:0
 ENG  18   5          Southampton             Brighton       1.68:1.02 |    2:2
 ENG  18   6               Fulham              Watford       1.55:1.48 |    1:1
 ENG  18   6              Cardiff             Man City       1.05:2.14 |    0:5
 ENG  18   6            Liverpool          Southampton       2.12:1.10 |    3:0
 ENG  18   6             Brighton            Tottenham       1.30:1.76 |    1:2
 ENG  18   6             West Ham              Chelsea       1.46:1.68 |    0:0
 ENG  18   6              Man Utd               Wolves       2.12:0.91 |    1:1
 ENG  18   6              Arsenal              Everton       1.86:1.30 |    2:0
 ENG  18   6              Burnley          Bournemouth       1.54:1.36 |    4:0
 ENG  18   6            Leicester         Huddersfield       1.88:1.00 |    3:1
 ENG  18   6       Crystal Palace            Newcastle       1.67:1.21 |    0:0
 ENG  18   7             West Ham              Man Utd       1.46:1.49 |    3:1
 ENG  18   7               Wolves          Southampton       1.42:1.45 |    2:0
 ENG  18   7              Cardiff              Burnley       1.26:1.46 |    1:2
 ENG  18   7              Chelsea            Liverpool       1.81:1.46 |    1:1
 ENG  18   7              Everton               Fulham       1.99:0.94 |    3:0
 ENG  18   7             Man City             Brighton       2.23:0.95 |    2:0
 ENG  18   7              Arsenal              Watford       2.00:1.09 |    2:0
 ENG  18   7         Huddersfield            Tottenham       1.18:1.74 |    0:2
 ENG  18   7            Newcastle            Leicester       1.51:1.38 |    0:2
 ENG  18   7          Bournemouth       Crystal Palace       1.65:1.24 |    2:1
 ENG  18   8            Leicester              Everton       1.64:1.35 |    1:2
 ENG  18   8              Watford          Bournemouth       1.59:1.33 |    0:4
 ENG  18   8            Tottenham              Cardiff       2.31:0.60 |    1:0
 ENG  18   8            Liverpool             Man City       1.94:1.59 |    0:0
 ENG  18   8          Southampton              Chelsea       1.39:1.64 |    0:3
 ENG  18   8       Crystal Palace               Wolves       1.78:1.05 |    0:1
 ENG  18   8               Fulham              Arsenal       1.27:1.72 |    1:5
 ENG  18   8              Burnley         Huddersfield       1.60:1.05 |    1:1
 ENG  18   8             Brighton             West Ham       1.40:1.31 |    1:0
 ENG  18   8              Man Utd            Newcastle       1.88:0.96 |    3:2
 ENG  18   9              Cardiff               Fulham       1.36:1.35 |    4:2
 ENG  18   9              Everton       Crystal Palace       1.74:1.10 |    2:0
 ENG  18   9         Huddersfield            Liverpool       1.13:1.73 |    0:1
 ENG  18   9            Newcastle             Brighton       1.58:1.10 |    0:1
 ENG  18   9             Man City              Burnley       2.12:0.94 |    5:0
 ENG  18   9              Arsenal            Leicester       1.80:1.22 |    3:1
 ENG  18   9             West Ham            Tottenham       1.44:1.49 |    0:1
 ENG  18   9               Wolves              Watford       1.47:1.36 |    0:2
 ENG  18   9          Bournemouth          Southampton       1.61:1.25 |    0:0
 ENG  18   9              Chelsea              Man Utd       1.82:1.28 |    2:2
 ENG  18  10            Tottenham             Man City       1.72:1.47 |    0:1
 ENG  18  10       Crystal Palace              Arsenal       1.43:1.45 |    2:2
 ENG  18  10            Liverpool              Cardiff       2.32:0.51 |    4:1
 ENG  18  10               Fulham          Bournemouth       1.35:1.44 |    0:3
 ENG  18  10            Leicester             West Ham       1.61:1.15 |    1:1
 ENG  18  10          Southampton            Newcastle       1.60:1.11 |    0:0
 ENG  18  10              Watford         Huddersfield       1.64:1.02 |    3:0
 ENG  18  10              Man Utd              Everton       1.76:1.17 |    2:1
 ENG  18  10             Brighton               Wolves       1.62:1.06 |    1:0
 ENG  18  10              Burnley              Chelsea       1.21:1.64 |    0:4
 ENG  18  11             Man City          Southampton       2.11:1.07 |    6:1
 ENG  18  11             West Ham              Burnley       1.64:1.01 |    4:2
 ENG  18  11              Arsenal            Liverpool       1.64:1.53 |    1:1
 ENG  18  11              Everton             Brighton       1.80:0.97 |    3:1
 ENG  18  11               Wolves            Tottenham       1.20:1.72 |    2:3
 ENG  18  11          Bournemouth              Man Utd       1.49:1.54 |    1:2
 ENG  18  11            Newcastle              Watford       1.56:1.19 |    1:0
 ENG  18  11              Cardiff            Leicester       1.11:1.66 |    0:1
 ENG  18  11         Huddersfield               Fulham       1.55:1.09 |    1:0
 ENG  18  11              Chelsea       Crystal Palace       2.00:0.98 |    3:1
 ENG  18  12       Crystal Palace            Tottenham       1.36:1.55 |    0:1
 ENG  18  12            Leicester              Burnley       1.76:1.03 |    0:0
 ENG  18  12              Cardiff             Brighton       1.25:1.39 |    2:1
 ENG  18  12            Liverpool               Fulham       2.20:0.73 |    2:0
 ENG  18  12          Southampton              Watford       1.66:1.17 |    1:1
 ENG  18  12              Arsenal               Wolves       2.04:0.92 |    1:1
 ENG  18  12             Man City              Man Utd       1.98:1.35 |    3:1
 ENG  18  12            Newcastle          Bournemouth       1.52:1.27 |    2:1
 ENG  18  12              Chelsea              Everton       1.93:1.15 |    0:0
 ENG  18  12         Huddersfield             West Ham       1.34:1.36 |    1:1
 ENG  18  13            Tottenham              Chelsea       1.77:1.48 |    3:1
 ENG  18  13              Everton              Cardiff       2.09:0.75 |    1:0
 ENG  18  13              Burnley            Newcastle       1.49:1.21 |    1:2
 ENG  18  13               Fulham          Southampton       1.37:1.45 |    3:2
 ENG  18  13              Man Utd       Crystal Palace       1.92:1.08 |    0:0
 ENG  18  13               Wolves         Huddersfield       1.55:1.21 |    0:2
 ENG  18  13             Brighton            Leicester       1.43:1.41 |    1:1
 ENG  18  13             West Ham             Man City       1.53:1.76 |    0:4
 ENG  18  13          Bournemouth              Arsenal       1.56:1.54 |    1:2
 ENG  18  13              Watford            Liverpool       1.38:1.72 |    0:3
 ENG  18  14       Crystal Palace              Burnley       1.59:1.04 |    2:0
 ENG  18  14            Newcastle             West Ham       1.47:1.24 |    0:3
 ENG  18  14              Cardiff               Wolves       1.35:1.34 |    2:1
 ENG  18  14         Huddersfield             Brighton       1.42:1.17 |    1:2
 ENG  18  14          Southampton              Man Utd       1.48:1.52 |    2:2
 ENG  18  14            Liverpool              Everton       1.95:1.17 |    1:0
 ENG  18  14             Man City          Bournemouth       2.19:1.14 |    3:1
 ENG  18  14              Arsenal            Tottenham       1.70:1.48 |    4:2
 ENG  18  14              Chelsea               Fulham       2.20:0.78 |    2:0
 ENG  18  14            Leicester              Watford       1.74:1.12 |    2:0
 ENG  18  15               Fulham            Leicester       1.30:1.45 |    1:1
 ENG  18  15             Brighton       Crystal Palace       1.40:1.22 |    3:1
 ENG  18  15               Wolves              Chelsea       1.20:1.76 |    2:1
 ENG  18  15              Everton            Newcastle       1.69:1.03 |    1:1
 ENG  18  15              Burnley            Liverpool       1.20:1.62 |    1:3
 ENG  18  15            Tottenham          Southampton       1.92:1.04 |    3:1
 ENG  18  15              Watford             Man City       1.38:1.78 |    1:2
 ENG  18  15          Bournemouth         Huddersfield       1.69:0.99 |    2:1
 ENG  18  15              Man Utd              Arsenal       1.76:1.33 |    2:2
 ENG  18  15             West Ham              Cardiff       1.84:0.78 |    3:1
 ENG  18  16              Arsenal         Huddersfield       1.95:0.88 |    1:0
 ENG  18  16              Man Utd               Fulham       2.05:0.83 |    4:1
 ENG  18  16              Everton              Watford       1.73:1.06 |    2:2
 ENG  18  16              Cardiff          Southampton       1.18:1.52 |    1:0
 ENG  18  16              Burnley             Brighton       1.47:1.09 |    1:0
 ENG  18  16            Newcastle               Wolves       1.66:1.02 |    1:2
 ENG  18  16              Chelsea             Man City       1.82:1.54 |    2:0
 ENG  18  16          Bournemouth            Liverpool       1.39:1.63 |    0:4
 ENG  18  16             West Ham       Crystal Palace       1.59:1.16 |    3:2
 ENG  18  16            Leicester            Tottenham       1.49:1.50 |    0:2
 ENG  18  17         Huddersfield            Newcastle       1.34:1.20 |    0:1
 ENG  18  17            Tottenham              Burnley       1.93:0.83 |    1:0
 ENG  18  17       Crystal Palace            Leicester       1.46:1.25 |    1:0
 ENG  18  17               Fulham             West Ham       1.31:1.40 |    0:2
 ENG  18  17          Southampton              Arsenal       1.44:1.41 |    3:2
 ENG  18  17             Man City              Everton       1.98:1.13 |    3:1
 ENG  18  17              Watford              Cardiff       1.80:0.82 |    3:2
 ENG  18  17             Brighton              Chelsea       1.19:1.62 |    1:2
 ENG  18  17               Wolves          Bournemouth       1.37:1.36 |    2:0
 ENG  18  17            Liverpool              Man Utd       1.84:1.27 |    3:1
 ENG  18  18              Cardiff              Man Utd       1.03:1.79 |    1:5
 ENG  18  18              Chelsea            Leicester       1.88:1.05 |    0:1
 ENG  18  18             Man City       Crystal Palace       2.08:1.01 |    2:3
 ENG  18  18              Everton            Tottenham       1.50:1.42 |    2:6
 ENG  18  18             West Ham              Watford       1.63:1.12 |    0:2
 ENG  18  18              Arsenal              Burnley       1.84:0.90 |    3:1
 ENG  18  18         Huddersfield          Southampton       1.33:1.31 |    1:3
 ENG  18  18          Bournemouth             Brighton       1.61:1.01 |    2:0
 ENG  18  18            Newcastle               Fulham       1.66:0.95 |    0:0
 ENG  18  18               Wolves            Liverpool       1.18:1.80 |    0:2
 ENG  18  19            Liverpool            Newcastle       1.85:0.83 |    4:0
 ENG  18  19             Brighton              Arsenal       1.19:1.38 |    1:1
 ENG  18  19               Fulham               Wolves       1.38:1.08 |    1:1
 ENG  18  19              Man Utd         Huddersfield       1.83:0.80 |    3:1
 ENG  18  19       Crystal Palace              Cardiff       1.66:0.73 |    0:0
 ENG  18  19          Southampton             West Ham       1.47:1.11 |    1:2
 ENG  18  19            Leicester             Man City       1.36:1.54 |    2:1
 ENG  18  19              Burnley              Everton       1.21:1.21 |    1:5
 ENG  18  19            Tottenham          Bournemouth       1.78:0.93 |    5:0
 ENG  18  19              Watford              Chelsea       1.22:1.48 |    1:2
 ENG  18  20              Watford            Newcastle       1.42:1.07 |    1:1
 ENG  18  20             Brighton              Everton       1.25:1.27 |    1:0
 ENG  18  20       Crystal Palace              Chelsea       1.24:1.46 |    0:1
 ENG  18  20          Southampton             Man City       1.34:1.62 |    1:3
 ENG  18  20              Man Utd          Bournemouth       1.77:1.02 |    4:1
 ENG  18  20            Liverpool              Arsenal       1.79:1.19 |    5:1
 ENG  18  20              Burnley             West Ham       1.32:1.17 |    2:0
 ENG  18  20            Leicester              Cardiff       1.77:0.73 |    0:1
 ENG  18  20            Tottenham               Wolves       1.98:0.79 |    1:3
 ENG  18  20               Fulham         Huddersfield       1.35:1.07 |    1:0
 ENG  18  21              Chelsea          Southampton       1.82:0.94 |    0:0
 ENG  18  21             Man City            Liverpool       1.80:1.40 |    2:1
 ENG  18  21             West Ham             Brighton       1.54:0.96 |    2:2
 ENG  18  21            Newcastle              Man Utd       1.28:1.43 |    0:2
 ENG  18  21          Bournemouth              Watford       1.50:1.07 |    3:3
 ENG  18  21         Huddersfield              Burnley       1.30:1.07 |    1:2
 ENG  18  21               Wolves       Crystal Palace       1.28:1.24 |    0:2
 ENG  18  21              Arsenal               Fulham       1.86:0.79 |    4:1
 ENG  18  21              Everton            Leicester       1.52:1.11 |    0:1
 ENG  18  21              Cardiff            Tottenham       0.94:1.73 |    0:3
 ENG  18  22              Burnley               Fulham       1.51:0.96 |    2:1
 ENG  18  22              Chelsea            Newcastle       1.85:0.83 |    2:1
 ENG  18  22              Cardiff         Huddersfield       1.20:1.20 |    0:0
 ENG  18  22              Everton          Bournemouth       1.61:1.06 |    2:0
 ENG  18  22            Leicester          Southampton       1.57:1.09 |    1:2
 ENG  18  22       Crystal Palace              Watford       1.50:1.08 |    1:2
 ENG  18  22             West Ham              Arsenal       1.43:1.38 |    1:0
 ENG  18  22             Man City               Wolves       2.15:0.81 |    3:0
 ENG  18  22            Tottenham              Man Utd       1.75:1.32 |    0:1
 ENG  18  22             Brighton            Liverpool       1.18:1.64 |    0:1
 ENG  18  23          Southampton              Everton       1.39:1.21 |    2:1
 ENG  18  23            Newcastle              Cardiff       1.60:0.71 |    3:0
 ENG  18  23              Watford              Burnley       1.45:0.99 |    0:0
 ENG  18  23              Man Utd             Brighton       1.82:0.87 |    2:1
 ENG  18  23            Liverpool       Crystal Palace       1.88:0.91 |    4:3
 ENG  18  23              Arsenal              Chelsea       1.49:1.37 |    2:0
 ENG  18  23          Bournemouth             West Ham       1.46:1.14 |    2:0
 ENG  18  23         Huddersfield             Man City       1.10:1.71 |    0:3
 ENG  18  23               Wolves            Leicester       1.20:1.33 |    4:3
 ENG  18  23               Fulham            Tottenham       1.09:1.62 |    1:2
 ENG  18  24            Tottenham              Watford       1.83:0.90 |    2:1
 ENG  18  24            Newcastle             Man City       1.19:1.60 |    2:1
 ENG  18  24            Liverpool            Leicester       1.84:1.01 |    1:1
 ENG  18  24              Arsenal              Cardiff       1.91:0.63 |    2:1
 ENG  18  24              Man Utd              Burnley       1.80:0.86 |    2:2
 ENG  18  24               Wolves             West Ham       1.26:1.26 |    3:0
 ENG  18  24          Bournemouth              Chelsea       1.25:1.44 |    4:0
 ENG  18  24          Southampton       Crystal Palace       1.45:1.06 |    1:1
 ENG  18  24         Huddersfield              Everton       1.15:1.27 |    0:1
 ENG  18  24               Fulham             Brighton       1.27:1.10 |    4:2
 ENG  18  25              Chelsea         Huddersfield       1.87:0.69 |    5:0
 ENG  18  25       Crystal Palace               Fulham       1.59:0.87 |    2:0
 ENG  18  25              Everton               Wolves       1.70:0.85 |    1:3
 ENG  18  25            Tottenham            Newcastle       1.78:0.85 |    1:0
 ENG  18  25              Cardiff          Bournemouth       1.09:1.36 |    2:0
 ENG  18  25              Burnley          Southampton       1.30:1.16 |    1:1
 ENG  18  25             Brighton              Watford       1.33:1.09 |    0:0
 ENG  18  25             West Ham            Liverpool       1.29:1.50 |    1:1
 ENG  18  25             Man City              Arsenal       1.82:1.16 |    3:1
 ENG  18  25            Leicester              Man Utd       1.44:1.36 |    0:1