# Heuers' statistical Football model

The following implementation aims to recreate the Football model of Prof. Dr. Andreas Heuer.

In [36]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from functools import lru_cache
import warnings
from sklearn.linear_model import LinearRegression

NUM_OF_COUNTRIES = 5
NUM_OF_SEASONS = 25
NUM_OF_MATCHES = 9130
NUM_OF_MATCHES_IN_A_SEASON = 1826
AVG_HF_ADV = 0.3672508214676889  # from DB
AVG_GA = 2.7175246440306681 # from DB
SEED = 1893

np.random.seed(SEED)
warnings.filterwarnings('ignore')

In [37]:
# Helperfunctions
def score_from_amount_and_diff(amount, diff):
    if diff < 0:
        home_score = (amount + diff) / 2
        away_score = home_score - diff
    else:
        away_score = (amount - diff) / 2
        home_score = away_score + diff

    # cut excess floating numbers
    if (home_score - int(home_score)) == 0 and (away_score - int(away_score)) == 0:
        home_score = int(home_score)
        away_score = int(away_score)
    
    return home_score, away_score


def print_formatted_pred_score(country, season, matchnumber, ht_name, at_name, ht_pred_score, at_pred_score, ht_actual_score, at_actual_score):
    print("%4s %3s %3s %20s %20s %15s | %6s" %
          (country, season, matchnumber, ht_name, at_name,
           str(ht_pred_score)[0:4] + ":" + str(at_pred_score)[0:4],
           f"{ht_actual_score}:{at_actual_score}"))

## Step 1 - Homefield advantage

In [38]:
df_country_season_homefield_adv = pd.read_csv("data/hf_adv.csv", sep=";")

df_country_season_homefield_adv

,country,season,matchnumber,ht_name,at_name,curr_hf_adv,past_hf_adv,actual_hf_adv
0,ENG,14,1,Arsenal,Crystal Palace,0.000000,0.0,1
1,ENG,14,1,Burnley,Chelsea,0.000000,0.0,-2
2,ENG,14,1,Leicester,Everton,0.000000,0.0,0
3,ENG,14,1,Liverpool,Southampton,0.000000,0.0,1
4,ENG,14,1,Man Utd,Swansea,0.000000,0.0,-1
...,...,...,...,...,...,...,...,...
9125,ITA,18,38,Fiorentina,CFC Genoa,0.275676,0.0,0
9126,ITA,18,38,Frosinone,Chievo,0.275676,0.0,0
9127,ITA,18,38,Inter,Empoli,0.275676,0.0,1
9128,ITA,18,38,Sampdoria,Juventus,0.275676,0.0,2
9129,ITA,18,38,SPAL Ferrara,AC Milan,0.275676,0.0,-1

In [39]:
@lru_cache(maxsize=None)
def h_country_season_homefield_adv(country, season, matchnumber):
    if season == 14 and matchnumber == 1:
        return AVG_HF_ADV
        
    sub_df = df_country_season_homefield_adv.query(
        f"season < {season} or (season == {season} and matchnumber < {matchnumber})")
        #f"country == '{country}' and season < {season} or (country == '{country}' and season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["past_hf_adv",
                "curr_hf_adv"]].values
    y = sub_df["actual_hf_adv"].values

    model = LinearRegression(positive=True).fit(X, y)
    # print("COEF | INTERCEPT",model.coef_, "|",model.intercept_)
    
    input_df = df_country_season_homefield_adv.query(
        f"country == '{country}' and season == {season} and matchnumber == {matchnumber}")
    input = input_df[["past_hf_adv",
                      "curr_hf_adv"]].values

    return model.predict(input)[0]

print("Homefield advantage:", h_country_season_homefield_adv("ESP", 14, 4))

Homefield advantage: 0.272108843537415

## Step 2 - Goalamount per match

In [40]:
df_country_season_goalamount = pd.read_csv(
    "data/ga.csv", sep=";")

df_country_season_goalamount

,country,season,matchnumber,ht_name,at_name,curr_ga,past_ga,actual_ga
0,ENG,14,1,Arsenal,Crystal Palace,0.000000,0.000000,3
1,ENG,14,1,Burnley,Chelsea,0.000000,0.000000,4
2,ENG,14,1,Leicester,Everton,0.000000,0.000000,4
3,ENG,14,1,Liverpool,Southampton,0.000000,0.000000,3
4,ENG,14,1,Man Utd,Swansea,0.000000,0.000000,3
...,...,...,...,...,...,...,...,...
9125,ITA,18,38,Fiorentina,CFC Genoa,2.675676,2.735965,0
9126,ITA,18,38,Frosinone,Chievo,2.675676,2.735965,0
9127,ITA,18,38,Inter,Empoli,2.675676,2.735965,3
9128,ITA,18,38,Sampdoria,Juventus,2.675676,2.735965,2
9129,ITA,18,38,SPAL Ferrara,AC Milan,2.675676,2.735965,5

In [41]:
@lru_cache(maxsize=None)
def h_country_season_goalamount(country, season, matchnumber):
    if season == 14 and matchnumber == 1:
        return AVG_GA
        
    sub_df = df_country_season_goalamount.query(
        f"season < {season} or (season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["past_ga",
                "curr_ga"]].values 
    y = sub_df["actual_ga"].values

    model = LinearRegression(positive=True).fit(X, y)
    # print("COEF | INTERCEPT",model.coef_, "-",model.intercept_)

    input_df = df_country_season_goalamount.query(
        f"country == '{country}' and season == {season} and matchnumber == {matchnumber}")
    input = input_df[["past_ga",
                      "curr_ga"]].values

    return model.predict(input)[0]


print("Goalamount:", h_country_season_goalamount("GER", 18, 18))

Goalamount: 2.7730362178156516

## Step 3: Teamstrength and expected goaldifference + Step 4: Specialty for promoters

In [42]:
df_matches = pd.read_csv('data/matches_heuer.csv', sep=';')

df_matches

,country,season,matchnumber,teamname,curr_eff_chancediff,past_chancediff_combined,curr_eff_chanceamount,past_chanceamount,curr_fitness,market_value_ln_relative,is_promoter,is_home,actual_goalamount,actual_goaldiff
0,ENG,14,1,Queens Park Rangers,0.000000,0.000000,0.000000,0.000000,0.000000,-0.392415,True,True,1,-1
1,ENG,14,1,Hull,0.000000,0.000000,0.000000,0.000000,0.000000,-0.348740,False,False,1,1
2,ENG,14,1,Newcastle,0.000000,0.000000,0.000000,0.000000,0.000000,-0.169272,False,True,2,-2
3,ENG,14,1,Man City,0.000000,0.000000,0.000000,0.000000,0.000000,1.002768,False,False,2,2
4,ENG,14,1,Burnley,0.000000,0.000000,0.000000,0.000000,0.000000,-1.140622,True,True,4,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18255,ITA,18,38,Napoli,5.242267,5.293421,3.415385,8.877193,3.375719,1.070083,False,False,5,-1
18256,ITA,18,38,Inter,2.881676,2.380263,1.042860,6.754386,1.768259,1.024225,False,True,3,1
18257,ITA,18,38,Empoli,-3.462648,-3.058772,-0.805584,4.403509,2.088522,-0.738824,True,False,3,-1
18258,ITA,18,38,Cagliari,-3.170633,-1.972368,-1.823289,4.824561,-3.719535,-0.358838,False,True,3,-1
18259,ITA,18,38,Udinese,-2.084748,-0.971053,-1.537836,5.000000,1.322783,-0.098958,False,False,3,1

In [43]:
@lru_cache(maxsize=None)
def h_teamstrength(country, season, matchnumber, teamname):
    if season == 14 and matchnumber == 1:
        return 0

    sub_df = df_matches.query(
        f"season < {season} and matchnumber == {matchnumber} or (season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["past_chancediff_combined",
                "curr_eff_chancediff", "curr_fitness", "market_value_ln_relative"]].values
    y = []

    # one team is only responsible for half of the goaldiff
    for index, row in sub_df.iterrows():
        goal_diff = row["actual_goaldiff"]
        if row["is_home"]:
            goal_diff -= AVG_HF_ADV # h_country_season_hf_adv
        else:
            goal_diff += AVG_HF_ADV  # h_country_season_hf_adv
        y.append(goal_diff/2)

    # w = closed_form_solution(X, y)
    model = LinearRegression(positive=True).fit(X, y)
    # print("COEF | INTERCEPT",model.coef_, "-",model.intercept_)

    input_df = df_matches.query(
        f"season == {season} and matchnumber == {matchnumber} and teamname == '{teamname}'")

    # Homefield advantage correction
    homefield_matches = df_matches.query(
        f"season == {season} and matchnumber < {matchnumber} and teamname == '{teamname}' and is_home").count()["is_home"]

    if matchnumber > 1:
        additional_homefield_matches = homefield_matches - \
            ((matchnumber - 1) - homefield_matches)
        if additional_homefield_matches > 0:
            input_df["curr_eff_chancediff"] -= (additional_homefield_matches * \
                h_country_season_homefield_adv(country, season, matchnumber) * 4) / (matchnumber - 1)

    # Step 4: Specialty for promoters
    if input_df.iloc[0]["is_promoter"]:
        input_df["past_chancediff_combined"] = input_df["past_chancediff_combined"] * \
            0.45 * model.coef_[1]
        input_df["curr_eff_chancediff"] = input_df["curr_eff_chancediff"] * 0.45 * model.coef_[1]

    input = input_df[["past_chancediff_combined",
                      "curr_eff_chancediff", "curr_fitness","market_value_ln_relative"]].values

    # teamstrength = np.dot(w, input.T)[0]
    teamstrength = model.predict(input)[0]

    if input_df.iloc[0]["is_promoter"]:
        teamstrength -= (13/34)

    return teamstrength

print("Teamstrength:", h_teamstrength("ENG", 16, 12, "Leicester"))

Teamstrength: -0.07783831347415164

## Step 5: Expected goalamount per match

In [44]:
@lru_cache(maxsize=None)
def h_goalamount_from_avg_per_match(country, season, matchnumber, teamname):
    if season == 14 and matchnumber == 1:
        return 0

    sub_df = df_matches.query(
        f"season < {season} and matchnumber == {matchnumber} or (season == {season} and matchnumber < {matchnumber})")

    X = sub_df[["past_chanceamount", "curr_eff_chanceamount"]].values 
    y = []
    for index, row in sub_df.iterrows():
        y.append(row["actual_goalamount"] - AVG_GA) # - h_country_season_goalamount()

    # w = closed_form_solution(X, y)
    model = LinearRegression(positive=True).fit(X, y)
    # print("COEF | INTERCEPT",model.coef_, "-",model.intercept_)

    input_df = df_matches.query(
        f"season == {season} and matchnumber == {matchnumber} and teamname == '{teamname}'")
    input = input_df[["past_chanceamount", "curr_eff_chanceamount"]].values

    # return np.dot(w, input.T)[0]
    return model.predict(input)[0]

print("Goalamount from avg:", h_goalamount_from_avg_per_match("GER", 16, 19, "Bayern"))

Goalamount from avg: 0.44263994387174

## Step 6: Predicted Goals

In [45]:
def predicted_goals(country, season, matchnumber, hometeam, awayteam):
    goalamount = h_goalamount_from_avg_per_match(
        country, season, matchnumber, hometeam) + h_goalamount_from_avg_per_match(country, season, matchnumber, awayteam) + h_country_season_goalamount(country, season, matchnumber)
    goaldiff = h_country_season_homefield_adv(country, season, matchnumber) + h_teamstrength(country, season, matchnumber, hometeam) - h_teamstrength(country, season, matchnumber, awayteam)
    return (goalamount, goaldiff)

## Step 7: Dependence on matchnumber

In [46]:
def matchnumber_goalamount_multiplier(country, matchnumber):
    # Uncertain
    if country == 'GER':
        if matchnumber < 18:
            return 1.02
        elif matchnumber < 31:
            return 0.95
        else:
            return 1.2
    else:
        if matchnumber < 19:
            return 1.02
        elif matchnumber < 35:
            return 0.95
        else:
            return 1.2

## Final: Full run on dataset to measure goalamount and goaldifference error

In [47]:
def predict(country, season, matchnumber, hometeam, awayteam):
    amount, diff = predicted_goals(country, season, matchnumber, hometeam, awayteam)

    home_score, away_score = score_from_amount_and_diff(amount, diff)

    home_score *= matchnumber_goalamount_multiplier(country, matchnumber)
    away_score *= matchnumber_goalamount_multiplier(country, matchnumber)

    return (home_score+ away_score), (home_score - away_score)

In [48]:
# For match in Dataset run prediction and measure error
do_a_whole_run = True

if not do_a_whole_run:
    print("Skipped testing run")

test_df = df_matches.query(f"season == 18")
ga_abs_error, gd_abs_error = 0, 0

if do_a_whole_run:
    for index, row in test_df.iterrows():
        if index % 2 == 0:
            home_score, away_score = score_from_amount_and_diff(
                row["actual_goalamount"], row["actual_goaldiff"])
            hometeam = row["teamname"]
            continue
        else:
            awayteam = row["teamname"]
            ga_pred, gd_pred = predict(
                row["country"], row["season"], row["matchnumber"], hometeam, awayteam)
            ga_abs_error += np.abs(ga_pred - row["actual_goalamount"])
            gd_abs_error += np.abs(gd_pred - row["actual_goaldiff"])
            h_score_pred, a_score_pred = score_from_amount_and_diff(ga_pred,gd_pred)
            print_formatted_pred_score(row["country"], row["season"], row["matchnumber"], hometeam, awayteam, h_score_pred ,a_score_pred, home_score, away_score)

    print("Absolute error goalamount",
          ga_abs_error / NUM_OF_MATCHES_IN_A_SEASON)
    print("Absolute error goaldiff", gd_abs_error / NUM_OF_MATCHES_IN_A_SEASON)

 ENG  18   1               Wolves              Everton       1.11:1.16 |    2:2
 ENG  18   1              Watford             Brighton       1.39:0.81 |    2:0
 ENG  18   1          Southampton              Burnley       1.49:0.79 |    0:0
 ENG  18   1            Newcastle            Tottenham       0.95:1.58 |    1:2
 ENG  18   1              Man Utd            Leicester       1.65:0.79 |    2:1
 ENG  18   1              Arsenal             Man City       1.33:1.43 |    0:2
 ENG  18   1         Huddersfield              Chelsea       0.80:1.58 |    0:3
 ENG  18   1               Fulham       Crystal Palace       1.16:1.06 |    0:2
 ENG  18   1          Bournemouth              Cardiff       1.54:0.70 |    2:0
 ENG  18   1            Liverpool             West Ham       1.94:0.61 |    4:0
 ENG  18   2            Tottenham               Fulham       1.94:0.55 |    3:1
 ENG  18   2              Everton          Southampton       1.53:0.96 |    2:1
 ENG  18   2             West Ham          Bournemouth       1.44:1.04 |    1:2
 ENG  18   2             Brighton              Man Utd       1.09:1.40 |    3:2
 ENG  18   2              Burnley              Watford       1.39:1.09 |    1:3
 ENG  18   2              Cardiff            Newcastle       1.12:1.36 |    0:0
 ENG  18   2              Chelsea              Arsenal       1.56:0.93 |    3:2
 ENG  18   2             Man City         Huddersfield       1.97:0.52 |    6:1
 ENG  18   2            Leicester               Wolves       1.68:0.80 |    2:0
 ENG  18   2       Crystal Palace            Liverpool       1.09:1.40 |    0:2
 ENG  18   3               Wolves             Man City       1.03:2.15 |    1:1
 ENG  18   3              Man Utd            Tottenham       1.66:1.64 |    0:3
 ENG  18   3         Huddersfield              Cardiff       1.30:0.87 |    0:0
 ENG  18   3          Bournemouth              Everton       1.51:1.33 |    2:2
 ENG  18   3            Newcastle              Chelsea       1.24:1.70 |    1:2
 ENG  18   3              Watford       Crystal Palace       1.62:1.11 |    2:1
 ENG  18   3              Arsenal             West Ham       1.80:1.08 |    3:1
 ENG  18   3            Liverpool             Brighton       2.22:0.69 |    1:0
 ENG  18   3          Southampton            Leicester       1.45:1.22 |    1:2
 ENG  18   3               Fulham              Burnley       1.22:1.21 |    4:2
 ENG  18   4              Watford            Tottenham       1.59:1.93 |    2:1
 ENG  18   4             Man City            Newcastle       2.40:1.10 |    2:1
 ENG  18   4             West Ham               Wolves       1.78:0.99 |    0:1
 ENG  18   4       Crystal Palace          Southampton       1.64:1.31 |    0:2
 ENG  18   4              Chelsea          Bournemouth       2.21:1.15 |    2:0
 ENG  18   4              Burnley              Man Utd       1.31:1.66 |    0:2
 ENG  18   4              Everton         Huddersfield       1.91:0.85 |    1:1
 ENG  18   4              Cardiff              Arsenal       1.05:1.88 |    2:3
 ENG  18   4             Brighton               Fulham       1.75:1.20 |    2:2
 ENG  18   4            Leicester            Liverpool       1.58:1.78 |    1:2
 ENG  18   5               Wolves              Burnley       1.33:1.04 |    1:0
 ENG  18   5         Huddersfield       Crystal Palace       1.25:1.16 |    0:1
 ENG  18   5            Tottenham            Liverpool       1.64:1.38 |    1:2
 ENG  18   5            Newcastle              Arsenal       1.27:1.44 |    1:2
 ENG  18   5              Everton             West Ham       1.55:0.98 |    1:3
 ENG  18   5          Bournemouth            Leicester       1.38:1.17 |    4:2
 ENG  18   5              Watford              Man Utd       1.27:1.41 |    1:2
 ENG  18   5              Chelsea              Cardiff       2.20:0.39 |    4:1
 ENG  18   5             Man City               Fulham       2.24:0.73 |    3:0
 ENG  18   5          Southampton             Brighton       1.53:0.91 |    2:2
 ENG  18   6               Fulham              Watford       1.34:1.31 |    1:1
 ENG  18   6              Cardiff             Man City       0.98:2.11 |    0:5
 ENG  18   6            Liverpool          Southampton       2.11:1.09 |    3:0
 ENG  18   6             Brighton            Tottenham       1.31:1.68 |    1:2
 ENG  18   6             West Ham              Chelsea       1.41:1.65 |    0:0
 ENG  18   6              Man Utd               Wolves       1.98:0.80 |    1:1
 ENG  18   6              Arsenal              Everton       1.87:1.28 |    2:0
 ENG  18   6              Burnley          Bournemouth       1.39:1.24 |    4:0
 ENG  18   6            Leicester         Huddersfield       1.74:0.88 |    3:1
 ENG  18   6       Crystal Palace            Newcastle       1.55:1.08 |    0:0
 ENG  18   7             West Ham              Man Utd       1.46:1.46 |    3:1
 ENG  18   7               Wolves          Southampton       1.42:1.40 |    2:0
 ENG  18   7              Cardiff              Burnley       1.21:1.44 |    1:2
 ENG  18   7              Chelsea            Liverpool       1.82:1.46 |    1:1
 ENG  18   7              Everton               Fulham       1.96:0.91 |    3:0
 ENG  18   7             Man City             Brighton       2.22:0.94 |    2:0
 ENG  18   7              Arsenal              Watford       1.95:1.11 |    2:0
 ENG  18   7         Huddersfield            Tottenham       1.22:1.69 |    0:2
 ENG  18   7            Newcastle            Leicester       1.48:1.36 |    0:2
 ENG  18   7          Bournemouth       Crystal Palace       1.62:1.23 |    2:1
 ENG  18   8            Leicester              Everton       1.77:1.45 |    1:2
 ENG  18   8              Watford          Bournemouth       1.72:1.41 |    0:4
 ENG  18   8            Tottenham              Cardiff       2.38:0.70 |    1:0
 ENG  18   8            Liverpool             Man City       2.18:1.87 |    0:0
 ENG  18   8          Southampton              Chelsea       1.50:1.78 |    0:3
 ENG  18   8       Crystal Palace               Wolves       1.86:1.13 |    0:1
 ENG  18   8               Fulham              Arsenal       1.40:1.83 |    1:5
 ENG  18   8              Burnley         Huddersfield       1.63:1.08 |    1:1
 ENG  18   8             Brighton             West Ham       1.45:1.33 |    1:0
 ENG  18   8              Man Utd            Newcastle       1.97:1.03 |    3:2
 ENG  18   9              Cardiff               Fulham       1.27:1.20 |    4:2
 ENG  18   9              Everton       Crystal Palace       1.72:1.06 |    2:0
 ENG  18   9         Huddersfield            Liverpool       1.15:1.74 |    0:1
 ENG  18   9            Newcastle             Brighton       1.51:1.03 |    0:1
 ENG  18   9             Man City              Burnley       2.10:0.88 |    5:0
 ENG  18   9              Arsenal            Leicester       1.83:1.22 |    3:1
 ENG  18   9             West Ham            Tottenham       1.51:1.59 |    0:1
 ENG  18   9               Wolves              Watford       1.34:1.21 |    0:2
 ENG  18   9          Bournemouth          Southampton       1.60:1.18 |    0:0
 ENG  18   9              Chelsea              Man Utd       1.80:1.25 |    2:2
 ENG  18  10            Tottenham             Man City       1.82:1.69 |    0:1
 ENG  18  10       Crystal Palace              Arsenal       1.46:1.54 |    2:2
 ENG  18  10            Liverpool              Cardiff       2.33:0.58 |    4:1
 ENG  18  10               Fulham          Bournemouth       1.28:1.45 |    0:3
 ENG  18  10            Leicester             West Ham       1.61:1.20 |    1:1
 ENG  18  10          Southampton            Newcastle       1.59:1.11 |    0:0
 ENG  18  10              Watford         Huddersfield       1.61:0.97 |    3:0
 ENG  18  10              Man Utd              Everton       1.75:1.25 |    2:1
 ENG  18  10             Brighton               Wolves       1.55:1.00 |    1:0
 ENG  18  10              Burnley              Chelsea       1.20:1.70 |    0:4
 ENG  18  11             Man City          Southampton       2.07:1.06 |    6:1
 ENG  18  11             West Ham              Burnley       1.60:0.89 |    4:2
 ENG  18  11              Arsenal            Liverpool       1.66:1.56 |    1:1
 ENG  18  11              Everton             Brighton       1.71:0.88 |    3:1
 ENG  18  11               Wolves            Tottenham       1.22:1.62 |    2:3
 ENG  18  11          Bournemouth              Man Utd       1.45:1.43 |    1:2
 ENG  18  11            Newcastle              Watford       1.45:1.10 |    1:0
 ENG  18  11              Cardiff            Leicester       0.99:1.59 |    0:1
 ENG  18  11         Huddersfield               Fulham       1.48:0.91 |    1:0
 ENG  18  11              Chelsea       Crystal Palace       1.95:0.92 |    3:1
 ENG  18  12       Crystal Palace            Tottenham       1.35:1.53 |    0:1
 ENG  18  12            Leicester              Burnley       1.80:0.90 |    0:0
 ENG  18  12              Cardiff             Brighton       1.16:1.36 |    2:1
 ENG  18  12            Liverpool               Fulham       2.20:0.68 |    2:0
 ENG  18  12          Southampton              Watford       1.60:1.14 |    1:1
 ENG  18  12              Arsenal               Wolves       2.01:0.89 |    1:1
 ENG  18  12             Man City              Man Utd       2.00:1.33 |    3:1
 ENG  18  12            Newcastle          Bournemouth       1.48:1.22 |    2:1
 ENG  18  12              Chelsea              Everton       1.94:1.10 |    0:0
 ENG  18  12         Huddersfield             West Ham       1.26:1.33 |    1:1
 ENG  18  13            Tottenham              Chelsea       1.80:1.60 |    3:1
 ENG  18  13              Everton              Cardiff       2.11:0.72 |    1:0
 ENG  18  13              Burnley            Newcastle       1.45:1.25 |    1:2
 ENG  18  13               Fulham          Southampton       1.34:1.46 |    3:2
 ENG  18  13              Man Utd       Crystal Palace       1.89:1.11 |    0:0
 ENG  18  13               Wolves         Huddersfield       1.49:1.18 |    0:2
 ENG  18  13             Brighton            Leicester       1.40:1.43 |    1:1
 ENG  18  13             West Ham             Man City       1.56:1.75 |    0:4
 ENG  18  13          Bournemouth              Arsenal       1.61:1.55 |    1:2
 ENG  18  13              Watford            Liverpool       1.41:1.73 |    0:3
 ENG  18  14       Crystal Palace              Burnley       1.57:1.04 |    2:0
 ENG  18  14            Newcastle             West Ham       1.50:1.19 |    0:3
 ENG  18  14              Cardiff               Wolves       1.32:1.28 |    2:1
 ENG  18  14         Huddersfield             Brighton       1.43:1.10 |    1:2
 ENG  18  14          Southampton              Man Utd       1.48:1.47 |    2:2
 ENG  18  14            Liverpool              Everton       1.93:1.16 |    1:0
 ENG  18  14             Man City          Bournemouth       2.14:1.09 |    3:1
 ENG  18  14              Arsenal            Tottenham       1.69:1.52 |    4:2
 ENG  18  14              Chelsea               Fulham       2.12:0.78 |    2:0
 ENG  18  14            Leicester              Watford       1.73:1.07 |    2:0
 ENG  18  15               Fulham            Leicester       1.19:1.36 |    1:1
 ENG  18  15             Brighton       Crystal Palace       1.32:1.14 |    3:1
 ENG  18  15               Wolves              Chelsea       1.11:1.66 |    2:1
 ENG  18  15              Everton            Newcastle       1.64:0.98 |    1:1
 ENG  18  15              Burnley            Liverpool       1.20:1.64 |    1:3
 ENG  18  15            Tottenham          Southampton       1.97:1.10 |    3:1
 ENG  18  15              Watford             Man City       1.31:1.74 |    1:2
 ENG  18  15          Bournemouth         Huddersfield       1.58:0.91 |    2:1
 ENG  18  15              Man Utd              Arsenal       1.76:1.34 |    2:2
 ENG  18  15             West Ham              Cardiff       1.76:0.73 |    3:1
 ENG  18  16              Arsenal         Huddersfield       1.90:0.87 |    1:0
 ENG  18  16              Man Utd               Fulham       2.00:0.76 |    4:1
 ENG  18  16              Everton              Watford       1.70:1.00 |    2:2
 ENG  18  16              Cardiff          Southampton       1.10:1.48 |    1:0
 ENG  18  16              Burnley             Brighton       1.38:1.06 |    1:0
 ENG  18  16            Newcastle               Wolves       1.60:0.94 |    1:2
 ENG  18  16              Chelsea             Man City       1.80:1.52 |    2:0
 ENG  18  16          Bournemouth            Liverpool       1.35:1.63 |    0:4
 ENG  18  16             West Ham       Crystal Palace       1.55:1.11 |    3:2
 ENG  18  16            Leicester            Tottenham       1.50:1.49 |    0:2
 ENG  18  17         Huddersfield            Newcastle       1.33:1.16 |    0:1
 ENG  18  17            Tottenham              Burnley       1.95:0.87 |    1:0
 ENG  18  17       Crystal Palace            Leicester       1.47:1.24 |    1:0
 ENG  18  17               Fulham             West Ham       1.24:1.42 |    0:2
 ENG  18  17          Southampton              Arsenal       1.46:1.45 |    3:2
 ENG  18  17             Man City              Everton       2.00:1.18 |    3:1
 ENG  18  17              Watford              Cardiff       1.73:0.83 |    3:2
 ENG  18  17             Brighton              Chelsea       1.20:1.60 |    1:2
 ENG  18  17               Wolves          Bournemouth       1.38:1.29 |    2:0
 ENG  18  17            Liverpool              Man Utd       1.86:1.31 |    3:1
 ENG  18  18              Cardiff              Man Utd       1.08:1.71 |    1:5
 ENG  18  18              Chelsea            Leicester       1.90:1.08 |    0:1
 ENG  18  18             Man City       Crystal Palace       2.10:1.04 |    2:3
 ENG  18  18              Everton            Tottenham       1.50:1.52 |    2:6
 ENG  18  18             West Ham              Watford       1.61:1.12 |    0:2
 ENG  18  18              Arsenal              Burnley       1.84:0.94 |    3:1
 ENG  18  18         Huddersfield          Southampton       1.32:1.29 |    1:3
 ENG  18  18          Bournemouth             Brighton       1.57:1.02 |    2:0
 ENG  18  18            Newcastle               Fulham       1.64:0.92 |    0:0
 ENG  18  18               Wolves            Liverpool       1.18:1.81 |    0:2
 ENG  18  19            Liverpool            Newcastle       1.86:0.80 |    4:0
 ENG  18  19             Brighton              Arsenal       1.18:1.36 |    1:1
 ENG  18  19               Fulham               Wolves       1.25:0.97 |    1:1
 ENG  18  19              Man Utd         Huddersfield       1.77:0.68 |    3:1
 ENG  18  19       Crystal Palace              Cardiff       1.68:0.59 |    0:0
 ENG  18  19          Southampton             West Ham       1.41:1.08 |    1:2
 ENG  18  19            Leicester             Man City       1.38:1.50 |    2:1
 ENG  18  19              Burnley              Everton       1.19:1.15 |    1:5
 ENG  18  19            Tottenham          Bournemouth       1.84:0.92 |    5:0
 ENG  18  19              Watford              Chelsea       1.19:1.43 |    1:2
 ENG  18  20              Watford            Newcastle       1.43:1.01 |    1:1
 ENG  18  20             Brighton              Everton       1.23:1.26 |    1:0
 ENG  18  20       Crystal Palace              Chelsea       1.25:1.47 |    0:1
 ENG  18  20          Southampton             Man City       1.39:1.61 |    1:3
 ENG  18  20              Man Utd          Bournemouth       1.84:0.93 |    4:1
 ENG  18  20            Liverpool              Arsenal       1.86:1.21 |    5:1
 ENG  18  20              Burnley             West Ham       1.27:1.18 |    2:0
 ENG  18  20            Leicester              Cardiff       1.78:0.68 |    0:1
 ENG  18  20            Tottenham               Wolves       2.03:0.75 |    1:3
 ENG  18  20               Fulham         Huddersfield       1.34:1.00 |    1:0
 ENG  18  21              Chelsea          Southampton       1.84:0.94 |    0:0
 ENG  18  21             Man City            Liverpool       1.76:1.47 |    2:1
 ENG  18  21             West Ham             Brighton       1.53:0.97 |    2:2
 ENG  18  21            Newcastle              Man Utd       1.23:1.48 |    0:2
 ENG  18  21          Bournemouth              Watford       1.46:1.11 |    3:3
 ENG  18  21         Huddersfield              Burnley       1.28:1.08 |    1:2
 ENG  18  21               Wolves       Crystal Palace       1.29:1.23 |    0:2
 ENG  18  21              Arsenal               Fulham       1.82:0.84 |    4:1
 ENG  18  21              Everton            Leicester       1.51:1.13 |    0:1
 ENG  18  21              Cardiff            Tottenham       0.93:1.75 |    0:3
 ENG  18  22              Burnley               Fulham       1.51:0.91 |    2:1
 ENG  18  22              Chelsea            Newcastle       1.88:0.83 |    2:1
 ENG  18  22              Cardiff         Huddersfield       1.18:1.18 |    0:0
 ENG  18  22              Everton          Bournemouth       1.60:1.08 |    2:0
 ENG  18  22            Leicester          Southampton       1.59:1.08 |    1:2
 ENG  18  22       Crystal Palace              Watford       1.50:1.05 |    1:2
 ENG  18  22             West Ham              Arsenal       1.45:1.40 |    1:0
 ENG  18  22             Man City               Wolves       2.14:0.82 |    3:0
 ENG  18  22            Tottenham              Man Utd       1.75:1.37 |    0:1
 ENG  18  22             Brighton            Liverpool       1.18:1.65 |    0:1
 ENG  18  23          Southampton              Everton       1.37:1.20 |    2:1
 ENG  18  23            Newcastle              Cardiff       1.53:0.68 |    3:0
 ENG  18  23              Watford              Burnley       1.36:0.95 |    0:0
 ENG  18  23              Man Utd             Brighton       1.76:0.80 |    2:1
 ENG  18  23            Liverpool       Crystal Palace       1.88:0.92 |    4:3
 ENG  18  23              Arsenal              Chelsea       1.53:1.44 |    2:0
 ENG  18  23          Bournemouth             West Ham       1.43:1.10 |    2:0
 ENG  18  23         Huddersfield             Man City       1.06:1.70 |    0:3
 ENG  18  23               Wolves            Leicester       1.11:1.31 |    4:3
 ENG  18  23               Fulham            Tottenham       1.09:1.63 |    1:2
 ENG  18  24            Tottenham              Watford       1.86:0.94 |    2:1
 ENG  18  24            Newcastle             Man City       1.21:1.62 |    2:1
 ENG  18  24            Liverpool            Leicester       1.87:1.03 |    1:1
 ENG  18  24              Arsenal              Cardiff       1.97:0.62 |    2:1
 ENG  18  24              Man Utd              Burnley       1.76:0.81 |    2:2
 ENG  18  24               Wolves             West Ham       1.20:1.23 |    3:0
 ENG  18  24          Bournemouth              Chelsea       1.29:1.44 |    4:0
 ENG  18  24          Southampton       Crystal Palace       1.45:1.06 |    1:1
 ENG  18  24         Huddersfield              Everton       1.12:1.27 |    0:1
 ENG  18  24               Fulham             Brighton       1.20:1.05 |    4:2
 ENG  18  25              Chelsea         Huddersfield       1.85:0.70 |    5:0
 ENG  18  25       Crystal Palace               Fulham       1.52:0.84 |    2:0
 ENG  18  25              Everton               Wolves       1.63:0.81 |    1:3
 ENG  18  25            Tottenham            Newcastle       1.83:0.92 |    1:0
 ENG  18  25              Cardiff          Bournemouth       1.02:1.36 |    2:0
 ENG  18  25              Burnley          Southampton       1.27:1.15 |    1:1
 ENG  18  25             Brighton              Watford       1.28:1.05 |    0:0
 ENG  18  25             West Ham            Liverpool       1.27:1.56 |    1:1
 ENG  18  25             Man City              Arsenal       1.87:1.24 |    3:1
 ENG  18  25            Leicester              Man Utd       1.38:1.32 |    0:1